version: "3"

services:
  postgres:
    container_name: postgres
    image: postgres:9.6
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
