# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import classipy_pb2 as classipy__pb2


class ImageClassifierStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Classify = channel.unary_unary(
        '/classipy.ImageClassifier/Classify',
        request_serializer=classipy__pb2.ImageRequest.SerializeToString,
        response_deserializer=classipy__pb2.ImageResult.FromString,
        )


class ImageClassifierServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Classify(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ImageClassifierServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Classify': grpc.unary_unary_rpc_method_handler(
          servicer.Classify,
          request_deserializer=classipy__pb2.ImageRequest.FromString,
          response_serializer=classipy__pb2.ImageResult.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'classipy.ImageClassifier', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
