# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: classipy.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='classipy.proto',
  package='classipy',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0e\x63lassipy.proto\x12\x08\x63lassipy\"I\n\x05Image\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0e\n\x06height\x18\x02 \x01(\r\x12\r\n\x05width\x18\x03 \x01(\r\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\x0c\"C\n\x0cImageRequest\x12\x12\n\nsender_pid\x18\x01 \x01(\t\x12\x1f\n\x06images\x18\x02 \x01(\x0b\x32\x0f.classipy.Image\"(\n\x14\x43lassificationResult\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\t\"x\n\x0bImageResult\x12\x12\n\nsender_pid\x18\x01 \x01(\t\x12\x37\n\x0f\x63lassifications\x18\x02 \x01(\x0b\x32\x1e.classipy.ClassificationResult\x12\x1c\n\x14total_execution_time\x18\x03 \x01(\r2N\n\x0fImageClassifier\x12;\n\x08\x43lassify\x12\x16.classipy.ImageRequest\x1a\x15.classipy.ImageResult\"\x00\x62\x06proto3')
)




_IMAGE = _descriptor.Descriptor(
  name='Image',
  full_name='classipy.Image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='filename', full_name='classipy.Image.filename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='classipy.Image.height', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='width', full_name='classipy.Image.width', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='classipy.Image.content', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=101,
)


_IMAGEREQUEST = _descriptor.Descriptor(
  name='ImageRequest',
  full_name='classipy.ImageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sender_pid', full_name='classipy.ImageRequest.sender_pid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='images', full_name='classipy.ImageRequest.images', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=170,
)


_CLASSIFICATIONRESULT = _descriptor.Descriptor(
  name='ClassificationResult',
  full_name='classipy.ClassificationResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='category', full_name='classipy.ClassificationResult.category', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=172,
  serialized_end=212,
)


_IMAGERESULT = _descriptor.Descriptor(
  name='ImageResult',
  full_name='classipy.ImageResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sender_pid', full_name='classipy.ImageResult.sender_pid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='classifications', full_name='classipy.ImageResult.classifications', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='total_execution_time', full_name='classipy.ImageResult.total_execution_time', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=214,
  serialized_end=334,
)

_IMAGEREQUEST.fields_by_name['images'].message_type = _IMAGE
_IMAGERESULT.fields_by_name['classifications'].message_type = _CLASSIFICATIONRESULT
DESCRIPTOR.message_types_by_name['Image'] = _IMAGE
DESCRIPTOR.message_types_by_name['ImageRequest'] = _IMAGEREQUEST
DESCRIPTOR.message_types_by_name['ClassificationResult'] = _CLASSIFICATIONRESULT
DESCRIPTOR.message_types_by_name['ImageResult'] = _IMAGERESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), {
  'DESCRIPTOR' : _IMAGE,
  '__module__' : 'classipy_pb2'
  # @@protoc_insertion_point(class_scope:classipy.Image)
  })
_sym_db.RegisterMessage(Image)

ImageRequest = _reflection.GeneratedProtocolMessageType('ImageRequest', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEREQUEST,
  '__module__' : 'classipy_pb2'
  # @@protoc_insertion_point(class_scope:classipy.ImageRequest)
  })
_sym_db.RegisterMessage(ImageRequest)

ClassificationResult = _reflection.GeneratedProtocolMessageType('ClassificationResult', (_message.Message,), {
  'DESCRIPTOR' : _CLASSIFICATIONRESULT,
  '__module__' : 'classipy_pb2'
  # @@protoc_insertion_point(class_scope:classipy.ClassificationResult)
  })
_sym_db.RegisterMessage(ClassificationResult)

ImageResult = _reflection.GeneratedProtocolMessageType('ImageResult', (_message.Message,), {
  'DESCRIPTOR' : _IMAGERESULT,
  '__module__' : 'classipy_pb2'
  # @@protoc_insertion_point(class_scope:classipy.ImageResult)
  })
_sym_db.RegisterMessage(ImageResult)



_IMAGECLASSIFIER = _descriptor.ServiceDescriptor(
  name='ImageClassifier',
  full_name='classipy.ImageClassifier',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=336,
  serialized_end=414,
  methods=[
  _descriptor.MethodDescriptor(
    name='Classify',
    full_name='classipy.ImageClassifier.Classify',
    index=0,
    containing_service=None,
    input_type=_IMAGEREQUEST,
    output_type=_IMAGERESULT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_IMAGECLASSIFIER)

DESCRIPTOR.services_by_name['ImageClassifier'] = _IMAGECLASSIFIER

# @@protoc_insertion_point(module_scope)
